Input_Paths:
  reference: "outgroup/21.fasta"
  outgroup_name: "hap21"
  distAngsd_path: "/projects/korneliussen/people/xcj389/distAngsd"

Parameters:
  art_l: 125
  art_m: 300
  art_s: 10
  bcftools_min_MQ: 30
  bcftools_min_BQ: 30
  angsd_min_MQ: 30
  angsd_min_BQ: 30
  angsd_only_proper_pairs: 0
  RAxML_threads: 3


Depths:
  - .5
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
  - 10.0
  - 11.0
  - 12.0
  - 13.0
  - 14.0
  - 15.0 
  - 16.0
  - 17.0
  - 18.0
  - 19.0
  - 20.0
  - 21.0
  - 22.0
  - 23.0
  - 24.0
  - 25.0
  - 26.0
  - 27.0
  - 28.0
  - 29.0
  - 30.0
  - 31.0
  - 32.0
  - 33.0
  - 34.0
  - 35.0

Individuals:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10


